//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRentACar.WF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
        public int AracId { get; set; }
        public string AracModel { get; set; }
        public System.DateTime AracEklenmeTarih { get; set; }
        public string AracMusaitlik { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Kiralama Kiralama { get; set; }
    }
}
