//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public int CarsId { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string Power { get; set; }
        public string Description { get; set; }
    }
}
